name: CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Deploy:
  name: Deploy
  runs-on: ubuntu-latest
  eps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"
    - name: Build
      run: scripts/buildprod.sh
